# Generated by Django 5.0.3 on 2024-03-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='donate',
            field=models.FloatField(null=True),
        ),
    ]
