# Generated by Django 5.0.3 on 2024-04-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_campaign_donate'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='goal',
            field=models.FloatField(null=True),
        ),
    ]
