# Generated by Django 5.0.3 on 2024-04-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_donors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='campaign',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donors',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
